---
apiVersion: v1
kind: Service
metadata:
  name: courses-svc
  labels:
    app: courses
    purpose: service
spec:
  ports:
    - port: 8080
  selector:
    app: courses
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-deploy
  labels:
    app: courses
    purpose: deploy
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: courses
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: courses-pod
      labels:
        app: courses
        version: dev1.0
    spec:
      containers:
        - image: shaikkhajaibrahim/courses
          name: courses-container
          ports:
            - containerPort: 8080
              name: coursesport
              protocol: TCP
          env:
            - name: MYSQL_SERVER
              value: mysql-svc
        
  