---
pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

trigger:
  - developer

stages:
  - stage: 'buildnpush'
    displayName: 'Build docker image and push'
    jobs:
      - job: 'buildnpush'
        displayName: 'Build docker image and push to registry'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker'
              repository: 'shaikkhajaibrahim/azdevopsstudentsregister'
              command: 'buildAndPush'
              tags: "latest"
          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              path: 'kubernetes'
      - job: 'qadeploy'
        displayName: 'Deploy to QA'
        steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'aksfromreleases'
              namespace: default
              command: 'apply'
              useConfigurationFile: true
              configurationType: configuration
              configuration: '$(System.DefaultWorkingDirectory)/**/mysql-deploy.yaml'
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'aksfromreleases'
              namespace: default
              command: 'apply'
              useConfigurationFile: true
              configurationType: configuration
              configuration: '$(System.DefaultWorkingDirectory)/**/scr-deploy.yaml'
              
              
