---
pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

trigger:
  - developer

stages:
  - stage: 'buildnpush'
    displayName: 'Build docker image and push'
    jobs:
      - job: 'buildnpush'
        displayName: 'Build docker image and push to registry'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker'
              repository: 'shaikkhajaibrahim/azdevopsstudentsregister'
              command: 'buildAndPush'
              tags: "$(Build.BuildId)"
