---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses
  labels:
    app: courses
    purpose: deploy
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: courses
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: courses-pod
      labels:
        app: courses
        version: dev1.0
    spec:
      containers:
        - image: courses
          name: courses-container
          ports:
            - containerPort: 8080
              name: coursesport
              protocol: TCP
          env:
            - name: MYSQL_SERVER
              value: mysql-svc
        
  